import Foundation

// https://www.ethervm.io/#opcodes
let OPCODE_TOOLTIP : [String: String] = [
  "STOP": "halts execution of the contract",
  "ADD": "(u)int256 addition modulo 2**256",
  "MUL":"(u)int256 multiplication modulo 2**256",
  "SUB":"(u)int256 subtraction modulo 2**256",
  "DIV":"uint256 division",
  "SDIV":"int256 division",
  "MOD":"",
  "SMOD":"",
  "ADDMOD":"",
  "MULMOD":"",
  "EXP":"",
  "SIGNEXTEND":"",
  "LT":"",
  "GT":"",
  "SLT":"",
  "SGT":"",
  "EQ":"",
  "ISZERO":"",
  "AND":"",
  "OR":"",
  "XOR":"",
  "NOT":"",
  "BYTE":"",
  "SHL":"",
  "SHR":"",
  "SAR":"",
  "SHA3":"",
  "ADDRESS":"",
  "BALANCE":"",
  "ORIGIN":"",
  "CALLER":"",
  "CALLVALUE":"",
  "CALLDATALOAD":"",
]
